# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8797c92c0849c2ee07df9a04314d16abebe4c176c99b6bd160579351fca5ad0b4af81cf1bd113c518b88de10190cea700794875f644ab16754af8aa72181b1ac

test:
  secret_key_base: b066cbd6ed01edff4ab1e629ad9ca62088e48d72e280286848b4ecdc35131221f8a96edd8d735b2c4b6ef29ba5dcf0898239df936333758a8b0aa3f124139f16

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
